# Generated by Django 4.1 on 2022-10-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Gmail', models.EmailField(max_length=200)),
                ('Add', models.CharField(max_length=200)),
            ],
        ),
    ]
