# Generated by Django 4.1 on 2022-10-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Age',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='SrNo',
            field=models.IntegerField(default=False),
        ),
    ]
